/* cg.c */
void cgtextseg();
void cgdataseg();
void cglitseg();
void cgfreeallregs(int keepreg);
int cgallocreg(int type);
void cgfreereg(int reg);
void cgspillregs();
void cgpreamble();
void cgpostamble();
void cgfuncpreamble(struct symtable *sym);
void cgfuncpostamble(struct symtable *sym);
int cgloadint(int value, int type);
int cgloadvar(struct symtable *sym, int op);
int cgloadglobstr(int label);
int cgadd(int r1, int r2, int type);
int cgsub(int r1, int r2, int type);
int cgmul(int r1, int r2, int type);
int cgdiv(int r1, int r2, int type);
int cgmod(int r1, int r2, int type);
int cgand(int r1, int r2, int type);
int cgor(int r1, int r2, int type);
int cgxor(int r1, int r2, int type);
int cginvert(int r, int type);
int cgshl(int r1, int r2, int type);
int cgshr(int r1, int r2, int type);
int cgnegate(int r, int type);
int cglognot(int r, int type);
int cgloadboolean(int r, int val, int type);
int cgboolean(int r, int op, int label, int type);
int cgcall(struct symtable *sym, int numargs, int *arglist, int *typelist);
int cgshlconst(int r, int val, int type);
int cgstorglob(int r, struct symtable *sym);
int cgstorlocal(int r, struct symtable *sym);
void cgglobsym(struct symtable *node);
void cgglobstr(int l, char *strvalue);
int cgcompare_and_set(int ASTop, int r1, int r2, int type);
void cglabel(int l);
void cgjump(int l);
int cgcompare_and_jump(int ASTop, int parentASTop,
				int r1, int r2, int label, int type);
int cgcast(int t, int oldtype, int newtype);
int cgwiden(int r, int oldtype, int newtype);
void cgreturn(int r, struct symtable *sym);
int cgaddress(struct symtable *sym);
int cgderef(int r, int type);
int cgstorderef(int r1, int r2, int type);
void cgswitch(int reg, int casecount, int toplabel, int *caselabel, int *caseval, int defaultlabel);
void cgmove(int r1, int r2, int type);
void cglinenum(int line);
